name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: V${{ github.run_number }}
          release_name: V${{ github.run_number }}
          body: ${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Publish
        id: publish_npm
        uses: author/action-publish@stable
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Rollback Release
       # if: failure() && steps.create_release.outputs.id != ''
       # uses: author/action-rollback@stable
      
        #with:
          # Using a known release ID
         # id: ${{ steps.create_release.id }}
          # Using a tag name
#tag: ${{ steps.autotagger.outputs.tagname }}
       # env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
